name: build-digipet
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        name: Build & push Docker image
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: docker/k8s/Dockerfile
          registry: gcr.io
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/digipet
          tag_with_sha: true
          tags: latest
